### ISSUE TITLE
Model bzg6 : mankout a ra ar restr words.txt ?

### ISSUE THREAD

**Issue by EwenKorr** [gweltou/Vosk-bzg#1]
Gant al logs : 

```
$ python test_wavefile.py ~/tmp/untitled2.wav
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from model/bzg6/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:279) Loading HCLG from model/bzg6/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:294) Loading words from model/bzg6/words.txt
ERROR: SymbolTable::ReadText: Can't open file: model/bzg6/words.txt
ERROR (VoskAPI:ReadDataFiles():model.cc:296) Could not read symbol table from file model/bzg6/words.txt
Traceback (most recent call last):
  File "/home/user/dev/gweltou/Vosk-bzg/test_wavefile.py", line 25, in <module>
    model = Model("model/bzg6")
  File "/home/user/.local/lib/python3.10/site-packages/vosk/__init__.py", line 57, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model
```

Mersi dit evit an repo-mañ ! :)

**Comment by gweltou** [comment]
Trugarez evit ho evezhiadenn @EwenKorr, reizhet eo !
